version: "3.8"
services:
  sandboxdocker:
    image: ghcr.io/joungwoo-pc/joungwoo-pc-open:b1152f39a63c08829d354178a1d195e86cd258f6
    container_name: sandboxdocker
    restart: always
    tty: true
    working_dir: /root/ext_volume
    environment:
      INTERNAL_LLM_API_BASE: "http://host.docker.internal:11434/v1"
      INTERNAL_LLM_API_KEY: "dev-key"
    volumes:
      - ${HOME}:/root/ext_volume
      - ./:/ext_src:ro
    ports:
      - "37910:37910"
      - "37911:37911"
      - "37912:37912"
      - "37913:37913"
      - "37914:37914"
      - "37915:37915"
      - "38010:38010"
      - "38011:38011"
    entrypoint: >
      bash -lc "
        if [ -f /ext_src/autorun.sh ]; then
          cp /ext_src/autorun.sh /root/autorun.sh;
        fi;
        if [ -f /root/autorun.sh ]; then
          chmod +x /root/autorun.sh || true;
          /root/autorun.sh || true;
        fi;
        exec sleep infinity
      "
