# .github/workflows/build.yml
# Build with the repo's Dockerfile (root), then upload sandboxdocker.tar and docker-compose.yml to Release (tag=build-latest).
# Run:
#   wget https://github.com/joungwoo-lee/joungwoo-lee-open/releases/download/build-latest/sandboxdocker.tar
#   wget https://github.com/joungwoo-lee/joungwoo-lee-open/releases/download/build-latest/docker-compose.yml
#   docker load -i sandboxdocker.tar
#   docker compose up -d

name: Publish Docker tar and compose to Release

on:
  push:
    branches: [ "main" ]
    paths:
      - "**"
      - ".github/workflows/build.yml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sanity check
        run: |
          set -euo pipefail
          test -f Dockerfile || { echo "Dockerfile not found at repo root"; exit 1; }
          ls -la || true

      # Build using the repo's Dockerfile (root)
      - name: Build Docker image
        run: docker build -t sandboxdocker:latest .

      - name: Save image as tar
        run: |
          docker save sandboxdocker:latest -o sandboxdocker.tar
          ls -lh sandboxdocker.tar

      # Compose has no entrypoint override; autorun is handled inside the image now.
      - name: Generate docker-compose.yml
        run: |
          cat > docker-compose.yml <<'EOF'
          version: "3.8"
          services:
            sandboxdocker:
              image: sandboxdocker:latest
              container_name: sandboxdocker
              restart: always
              tty: true
              working_dir: /root/ext_volume
              environment:
                INTERNAL_LLM_API_BASE: "http://host.docker.internal:11434/v1"
                INTERNAL_LLM_API_KEY: "dev-key"
              volumes:
                - ${HOME}:/root/ext_volume
              ports:
                - "37910:37910"
                - "37911:37911"
                - "37912:37912"
                - "37913:37913"
                - "37914:37914"
                - "37915:37915"
                - "38010:38010"
                - "38011:38011"
          EOF

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-latest
          name: build-latest
          make_latest: true
          prerelease: false
          files: |
            sandboxdocker.tar
            docker-compose.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
